### ISSUE TITLE
Various enhancements

### ISSUE THREAD

**Issue by compor** [compor/IteratorRecognition#2]
Various enhancements suggested by @robcasloz

1. Make it clearer in the Requirements section that LLVM needs to be
built with -DBUILD_SHARED_LIBS=1 if the passes are to be used as plug-ins.

2. List Pedigree as a requirement for the IteratorRecognition pass.

3. Perhaps set -DCMAKE_EXPORT_COMPILE_COMMANDS to 1 by default (the
build just fails otherwise because compile_commands.json is expected at
some point but it is not generated).

4. You could update the "How to execute" part with more self-contained
commands, to get the user started quickly. For example:

Pedigree: opt -load $PEDIGREE_PREFIX/lib/libLLVMPedigreePass.so -basicaa
-pedigree-mdg-dfs-enumerate -pedigree-mdg-dot tests/lenherr2008_fig01.ll

IteratorRecognition: opt -load
$PEDIGREE_PREFIX/lib/libLLVMPedigreePass.so -load
$ITERATOR_RECOGNITION_PREFIX/lib/libLLVMIteratorRecognitionPass.so
-basicaa -globals-aa -scev-aa -tbaa -itr-annotate -S
unittests/data/test01.ll

5. The "How to execute" example for IteratorRecognition is broken:
opt: Unknown command line argument '-itr'.  Try: 'opt -help'

**Comment by compor** [comment]
Converting comments to separate work items:

- [x]  You could update the "How to execute" part with more self-contained commands, to get the user started quickly. For example:
  - Pedigree: 
  `opt -load $PEDIGREE_PREFIX/lib/libLLVMPedigreePass.so -basicaa -pedigree-mdg-dfs-enumerate -pedigree-mdg-dot tests/lenherr2008_fig01.ll`
  - IteratorRecognition:  
`opt -load $PEDIGREE_PREFIX/lib/libLLVMPedigreePass.so -load $ITERATOR_RECOGNITION_PREFIX/lib/libLLVMIteratorRecognitionPass.so -basicaa -globals-aa -scev-aa -tbaa -itr-annotate -S unittests/data/test01.ll`
- [x] Perhaps set `-DCMAKE_EXPORT_COMPILE_COMMANDS` to `On` by default (the
build just fails otherwise because `compile_commands.json` is expected at
some point but it is not generated).
- [x] Make it clearer in the Requirements section that LLVM needs to be built with `-DBUILD_SHARED_LIBS=On` if the passes are to be used as plug-ins.
- [x]  List Pedigree as a requirement for the IteratorRecognition pass.
- [x] The "How to execute" example for IteratorRecognition is broken:  
```opt: Unknown command line argument '-itr'. Try: 'opt -help'```

**Comment by compor** [comment]
@robcasloz, can you please provide some additional feedback on the below (where necessary)? :smile: 

- Would it suffice if we just referred to the run scripts directory (./utils/scripts/run/) which contains example incantations of more complex and common uses?
- Reproduced :+1: will fix
- Agreed :+1: 
  However, it's worth mentioning that it is a restriction of how dynamic loading works in general. I think it's unfortunate, because the only way for a pass to work regardless of the value set in `BUILD_SHARED_LIBS` is to have it in-tree.
- Agreed :+1: 
- Agreed :+1:

**Comment by robcasloz** [comment]
Regarding the first point, I had actually overlooked those scripts. Yes, I agree, that would be even more useful.
Regarding the third point, I agree that it is a general restriction but it would still be helpful to have a reminder I think.
Thanks for the hard work you put into this!

**Comment by compor** [comment]
Thanks, I'll put them in the back-burner.
